# Generated by Django 5.0.1 on 2024-03-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignDocumentsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador Unico')),
                ('reference', models.CharField(choices=[('RED INTA 2022', 'Red INTA 2022'), ('INTA LABOULAYE', 'INTA Laboulaye')], default='Seleccionar', max_length=50, verbose_name='Org. de Referencia')),
                ('paper_type', models.CharField(choices=[('VARIEDADES', 'Variedades')], default='Seleccionar', max_length=50, verbose_name='Tipo de ensayo')),
                ('paper_creation_year', models.DateField(verbose_name='Año de registro')),
                ('location_origing', models.CharField(choices=[('ADELIA MARIA', 'Adelia Maria'), ('BELL VILLE', 'Bell Ville'), ('JUSTINIANO POSSE', 'Justiniano Posse'), ('LA CARLOTA', 'La Carlota'), ('LABOULAYE', 'Laboulaye'), ('MARCOZ JUAREZ', 'Marcos Juarez'), ('ONAGOITY', 'Onagoity')], default='Seleccionar', max_length=50, verbose_name='Localidad de origen')),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Coordenada de Latitud')),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Coordenada de Longitud')),
                ('paper_repetition', models.IntegerField(default=1, verbose_name='Repeticiones del ensayo')),
                ('crop_variety', models.CharField(choices=[('BUCKSY200', 'Buck SY 200'), ('LENOX', 'Lenox'), ('ACA360', 'ACA 360'), ('ACA365', 'ACA 365'), ('ALGARROBO', 'Algarrobo'), ('ARSLAK', 'Arslak'), ('BAGUETTE601', 'Baguette 601'), ('BASILIO', 'Basilio'), ('BG620', 'Bg 620'), ('BG750', 'Bg 750'), ('BIOINTA2004', 'Biointa 2004'), ('BIOINTA3005', 'Biointa 3005'), ('BIOINTA3006', 'Biointa 3006'), ('CEDRO', 'Cedro'), ('FLORIPAND', 'Floripan 200'), ('GUAYABO', 'Guayabo'), ('MSINTA119', 'MS INTA 119'), ('ÑANDUBAY', 'Ñandubay'), ('SURSEM2330', 'Sursem 2330')], default='Seleccionar', max_length=50, verbose_name='Variedad del cultivo')),
                ('humidity_percentage_stat', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje de humedad')),
                ('performance_stat', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Rendimiento')),
                ('relative_performance_stat', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Rendimiento relativo')),
                ('grain_count_crop_stat', models.IntegerField(verbose_name='Conteo de granos por cultivo')),
                ('grain_count_per_spike_stat', models.IntegerField(verbose_name='Conteo de granos por espiga')),
                ('weight_per_thousand_grains_stat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso por mil granos')),
                ('proteins_percentage_stat', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Porcentaje de proteinas')),
                ('ph_stat', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Potencial de hidrogeno')),
            ],
            options={
                'db_table': 'campaign_documents',
            },
        ),
    ]
