# Generated by Django 5.0.1 on 2024-03-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigndocumentsmodel',
            name='humidity_percentage_stat',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje de humedad (%)'),
        ),
        migrations.AlterField(
            model_name='campaigndocumentsmodel',
            name='performance_stat',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Rendimiento (Kg/Ha)'),
        ),
        migrations.AlterField(
            model_name='campaigndocumentsmodel',
            name='ph_stat',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Potencial de hidrogeno (ph)'),
        ),
        migrations.AlterField(
            model_name='campaigndocumentsmodel',
            name='proteins_percentage_stat',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Porcentaje de proteinas (%)'),
        ),
        migrations.AlterField(
            model_name='campaigndocumentsmodel',
            name='relative_performance_stat',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Rendimiento relativo (kg/ha)'),
        ),
        migrations.AlterField(
            model_name='campaigndocumentsmodel',
            name='weight_per_thousand_grains_stat',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso por mil granos (g)'),
        ),
    ]
