# Generated by Django 5.0.1 on 2024-05-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_alter_campaigndocumentsmodel_humidity_percentage_stat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarietyOptionsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificado unico')),
                ('tradename', models.CharField(default='--Tipear--', max_length=25, verbose_name='Nombre comercial de la variante')),
                ('variant_name', models.CharField(default='--Tipear--', max_length=25, verbose_name='Nombre especifico de la variante')),
            ],
            options={
                'db_table': 'variety_options',
            },
        ),
        migrations.AlterField(
            model_name='campaigndocumentsmodel',
            name='crop_variety',
            field=models.CharField(choices=[('BUCKSY200', 'Buck SY 200'), ('LENOX', 'Lenox'), ('ACA360', 'ACA 360'), ('ACA365', 'ACA 365'), ('ALGARROBO', 'Algarrobo'), ('ARSLAK', 'Arslak'), ('BAGUETTE601', 'Baguette 601'), ('BASILIO', 'Basilio'), ('BG620', 'Bg 620'), ('BG750', 'Bg 750'), ('BIOINTA2004', 'Biointa 2004'), ('BIOINTA3005', 'Biointa 3005'), ('BIOINTA3006', 'Biointa 3006'), ('CEDRO', 'Cedro'), ('FLORIPAND', 'Floripan 200'), ('GUAYABO', 'Guayabo'), ('MSINTA119', 'MS INTA 119'), ('ÑANDUBAY', 'Ñandubay'), ('SURSEM2330', 'Sursem 2330')], default='--Seleccionar--', max_length=50, verbose_name='Variedad del cultivo'),
        ),
    ]
