# Generated by Django 5.0.1 on 2024-05-30 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_locationoptionsmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigndocumentsmodel',
            name='location_origing',
        ),
        migrations.AddField(
            model_name='campaigndocumentsmodel',
            name='location_origin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='location_origin', to='repository.locationoptionsmodel', verbose_name='Localidad de origen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaigndocumentsmodel',
            name='crop_variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_variety', to='repository.varietyoptionsmodel', verbose_name='Variedad del cultivo'),
        ),
    ]
